### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by rasod** [kevinjohncutler/colormixing#1]
Not an issue just a thank you for your updated color mixing code.
I had no idea what I was doing when I tried to come up with the HSI to RGBWW algorithm.
I wrote most of it on a plane on an iPad, I was surprised it worked at all.

"If you want the right answer, post the wrong one on the internet"

**Comment by kevinjohncutler** [comment]
Thanks for saying so! You code helped a lot early on to understand the basics and orient myself to C :) not only that but it kept the lights on in the meantime haha.
